#!/usr/bin/env bash

STEP_SIZE=${STEP_SIZE:-5}

case $BLOCK_BUTTON in
  3) light -S 0 ;; # right click
  4) light -A "$STEP_SIZE" ;; # scroll up
  5) light -U "$STEP_SIZE" ;; # scroll down, decrease
esac


BRIGHTNESS=$(light -G)
echo " ${BRIGHTNESS}%"
